@startuml

entity songplays{
    songplay_id : SERIAL <<PK>>
    --
    start_time : bigint
    user_id : int <<FK>>
    level : char(4)  <<free|paid>>
    song_id : varchar <<FK>>
    artist_id : varchar <<FK>>
    session_id : int 
    location : varchar
    user_agent : varchar 
}

entity users{
    user_id : int <<PK>>
    --
    first_name : varchar 
    last_name : varchar 
    gender : char(1) <<M|F>>
    level : char(4) <<free|paid>>
}

entity artists{
    artist_id : varchar <<PK>>
    --
    name : varchar 
    location : varchar
    latitude : real
    longitude : real
}

entity time{
    start_time : bigint <<PK>>
    --
    hour : int 
    day : int 
    week : int 
    month : varchar 
    year : int 
    weekday : varchar 
}

entity songs{
    song_id : varchar <<PK>>
    --
    artist_id : varchar <<FK>>
    year : int
    duration : real 
    title : varchar 
}

songplays }o--|| users
songplays }o--|| songs 
songplays }o--|| artists
songs }|--|{ artists

@enduml